name: "UPWORK SREDIO TASK MAIN"

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - closed

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      - name: Send In Progress Notification
        uses: imfaisii/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: "started"
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /home/imfaisii-sredio-task/htdocs/sredio-task.imfaisii.dev/upwork-sredio-integration-task/frontend/dist/frontend
            git stash
            git pull
            npm i
            npm run build
            cp /home/imfaisii-sredio-task/htdocs/sredio-task.imfaisii.dev/upwork-sredio-integration-task/frontend/.htaccess /home/imfaisii-sredio-task/htdocs/sredio-task.imfaisii.dev/upwork-sredio-integration-task/frontend/dist/frontend
            cd /home/imfaisii-api-sredio-task/htdocs/api-sredio-task.imfaisii.dev/upwork-sredio-integration-task/backend
            git stash
            git pull
            pnpm i
            pm2 restart upwork-sredio-app
      - name: Send Success Notification
        if: success()
        uses: imfaisii/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: "success"
      - name: Send Failure Notification
        if: failure()
        uses: imfaisii/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: "failure"
